export class LanguageFile {
  /**
   * NOTICE : keys should be lowercase
   */
  public static language = {
    "cancel": { "fa": "لغو", "en": "Cancel" },
    "ok": { "fa": "تایید", "en": "OK" },
    "width": { "fa": "عرض", "en": "Width" },
    "width :": { "fa": "عرض :", "en": "Width :" },
    "stop color :": { "fa": "x", "en": "x" },
    "height :": { "fa": "ارتفاع :", "en": "Height :" },
    "color :": { "fa": "رنگ :", "en": "Color :" },
    "stroke width :": { "fa": "مقدار ضحامت :", "en": "Stroke Width :" },
    "stroke color :": { "fa": "رنگ ضخامت :", "en": "Stroke Color :" },
    "opacity :": { "fa": "شفافیت :", "en": "Opacity :" },
    "show/hide layer": { "fa": "نمایش/مخفی لایر", "en": "Show/Hide Layer" },
    "layer forward": { "fa": "آوردن به جلو لایر", "en": "Layer Forward" },
    "print": { "fa": "چاپ", "en": "Print" },
    "multiple page": { "fa": "چند صفحه", "en": "Multiple Page" },
    "new": { "fa": "جدید", "en": "New" },
    "clear": { "fa": "پاک کردن", "en": "Clear" },
    "save": { "fa": "ذخیره", "en": "Save" },
    "load": { "fa": "بارگزاری", "en": "Load" },
    "change style": { "fa": "تغییرات ظاهری", "en": "Change Style" },
    "change childs style": { "fa": "تغییرات ظاهری جزییات", "en": "Change Childs Style" },
    "parent": { "fa": "والد", "en": "Parent" },
    "toolbar": { "fa": "نوار ابزار", "en": "Toolbar" },
    "shape": { "fa": "شکل", "en": "Shape" },
    "gradient": { "fa": "گرادیانت", "en": "Gradient" },
    "animation": { "fa": "انیمیشن", "en": "Animation" },
    "childs": { "fa": "جزییات", "en": "Childs" },
    "apply changes": { "fa": "اعمال تغییرات", "en": "Apply Changes" },
    "home": { "fa": "خانه", "en": "Home" },
    "run mode": { "fa": "اجرا", "en": "Run Mode" },
    "design mode": { "fa": "طراحی", "en": "Design Mode" },
    "loaddiagram": { "fa": "بارگزاری", "en": "Load Diagram" },
    "loaddiagramtip": { "fa": "بارگزاری طراحی", "en": "Load Saved Diagram" },
    "export": { "fa": "خروجی", "en": "Export" },
    "basic shapes": { "fa": "اشکال پایه", "en": "Basic Shapes" },
    "tank shapes": { "fa": "تانکر ها", "en": "Tank Shapes" },
    "fan shapes": { "fa": "پنکه ها", "en": "Fan Shapes" },
    "pipe shapes": { "fa": "لوله ها", "en": "Pipe Shapes" },
    "motor shapes": { "fa": "موتورها", "en": "Motor Shapes" },
    "industry-shapes": { "fa": "اشکال صنعتی", "en": "Industry Shapes" },
    "industry shapes": { "fa": "اشکال صنعتی", "en": "Industry Shapes" },
    "turibines": { "fa": "توربین ها", "en": "Turbine" },
    "connectors": { "fa": "اتصالات", "en": "Connectors" },
    "isactive": { "fa": "تست", "en": "Test" },
    "delay": { "fa": "تاخیر", "en": "Delay" },
    "isloop": { "fa": "ادامه دار", "en": "Loop" },
    "angel": { "fa": "زاویه", "en": "Angel" },
    "rotate": { "fa": "گردش", "en": "Rotate" },
    "move": { "fa": "انتقال", "en": "Move" },
    "change width": { "fa": "تغییر عرض", "en": "Change Width" },
    "change height": { "fa": "تغییر عرض", "en": "Change Height" },
    "blink": { "fa": "چشمک زن", "en": "Blink" },
    "height": { "fa": "ارتفاع", "en": "Height" },
    "choose an option": { "fa": "انتخاب کنید", "en": "Choose an option" },
    "firstangel": { "fa": "زاویه شروع", "en": "Start Angel" },
    "secondangel": { "fa": "زاویه پایان", "en": "End Angel" },
    "gauge": { "fa": "گیج", "en": "Gauge" },
    "x": { "fa": "X", "en": "X" },
    "text": { "fa": "متن", "en": "Text" },
    "fontstyle": { "fa": "فونت", "en": "Font Style" },
    "fontstyle :": { "fa": "فونت :", "en": "Font Style :" },
    "fontweight": { "fa": "پهنای فونت", "en": "Font Weight" },
    "fontweight :": { "fa": "پهنای فونت :", "en": "Font Weight :" },
    "fontsize": { "fa": "اندازه فونت", "en": "Font Size" },
    "fontsize :": { "fa": "اندازه فونت :", "en": "Font Size" },
    "fontfamily": { "fa": "نام فونت", "en": "Font Family" },
    "fontfamily :": { "fa": "نام فونت :", "en": "Font Family" },
    "image": { "fa": "عکس", "en": "Image" },
    "fire": { "fa": "آتش", "en": "Fire" },
    "coolingandheating": { "fa": "گرمایش و سرمایش", "en": "Cooling and Heating" },
    "pumps": { "fa": "پمپ", "en": "Pumps" },
    "valve": { "fa": "Valve", "en": "Valve" },
    "other": { "fa": "سایر", "en": "Other" },
    "link :": { "fa": "پیوند :", "en": "Link :" },
    "link": { "fa": "پیوند", "en": "Link" },
    "file :": { "fa": "فایل :", "en": "File :" },
    "file": { "fa": "فایل", "en": "File" },
    "saveditem": { "fa": "لیست فایلها", "en": "Saved Items" },
    "success": { "fa": "موفق", "en": "Success" },
    "failure": { "fa": "ناموفق", "en": "Failure" },
    "warning": { "fa": "هشدار", "en": "Warning" },
    "info": { "fa": "اطلاعیه", "en": "Info" },
    "confirm": { "fa": "تاییدیه", "en": "Confirm" },
    "no": { "fa": "خیر", "en": "No" },
    "yes": { "fa": "بله", "en": "yes" },
    "successoperation": { "fa": "عملیات با موفقیت انجام شد", "en": "Success Operation" },
    "operationfailed": { "fa": "خطا در عملیات!!", "en": "Operation Failed" },
    "insert-new-value": { "fa": "مقدار جدید را وارد کنید", "en": "Insert the new value" },
    "new-value": { "fa": "مقدار جدید", "en": "New value" },
    "send-command": { "fa": "ارسال فرمان", "en": "Send Command" },
    "selectanoption": { "fa": "یک گزینه را انتخاب کنید!", "en": "Select an option" },
    "howtosave": { "fa": "نحوه ذخیره", "en": "How to save?" },
    "howtoload": { "fa": "نحوه بارگذاری", "en": "How to load" },
    "filename": { "fa": "نام فایل", "en": "File Name" },
    "name": { "fa": "نام", "en": "Name" },
    "icon": { "fa": "آیکون", "en": "Icon" },
    "title": { "fa": "عنوان", "en": "Title" },
    "description": { "fa": "توضیحات", "en": "Description" },
    "continiue": { "fa": "ادامه", "en": "Continue" },
    "custom": { "fa": "سفارشی", "en": "Custom" },
    "import": { "fa": "بار گذاری", "en": "Import" },
    "layers": { "fa": "لایه ها", "en": "Layers" },
    "layer": { "fa": "لایه", "en": "Layer" },
    "visible": { "fa": "قابل نمایش", "en": "Visible" },
    "lock": { "fa": "قفل", "en": "Lock" },
    "bringtofront": { "fa": "آوردن به جلو", "en": "Bring To Front" },
    "sendtoback": { "fa": "ارسال به پشت", "en": "Send To Back" },
    "setactive": { "fa": "فعال کردن", "en": "Set As Active" },
    "addnewlayer": { "fa": "لایه جدید", "en": "Add New Layer" },
    "hideotherlayers": { "fa": "مخفی کردن سایر لایه ها", "en": "Hide Other Layers" },
    "y": { "fa": "Y", "en": "Y" },

  };
}
